### ISSUE TITLE
Set up Kanban Project

### ISSUE THREAD

**Issue by kelvinbush** [kelvinbush/catalog-capstone#35]
In this review request we set up the Kanban board for out project.
Here is the [link](https://github.com/kelvinbush/catalog-capstone/projects/1?query=is%3Aopen+sort%3Aupdated-desc) to our GitHub project.
We are a team of 3 members.
`Team member #1` - @kelvinbush
`Team member #2` - @AbuRayhaan
`Team member #3` - @SimbaWANGU

**Comment by rotimiazeez** [comment]
# Hi TEAM 👏🏽, 
## Good job so far! 👍🏽 
### Summary ♨️ 
- Great job adding the project link✔️ 
- Good and descriptive PR 💯 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️
_Check the comments under the review._
- [ ] Kindly make sure the tasks are evenly distributed amongst team members. I'd suggest you re-assign the tasks and make sure each member has equal tasks.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zhadier** [comment]
## Hi @kelvinbush @SimbaWANGU  & @AbuRayhaan  👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>

# Congratulations! 🎉 

✔️ Great job with the task management and distribution

### Keep Rocking!👏👏👏
## Optional
<hr/>

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
